### ISSUE TITLE
change to html syntax

### ISSUE THREAD

**Issue by bminixhofer** [MEH-Design/frix#15]
Instead of this
````
{{oHeader as title}}
````
we now want this
````
<cms-organism type="header" name="title" />
````

Also, attributes can be "passed down" using "cms-*".

For example
````
<cms-organism type="header" name="title" cms-text="lorem"/>
````
would override the default text attribute.

**Comment by bminixhofer** [comment]
Will leave this open although we have already practically switched to remind of merging into `master` branch.

**Comment by MiniXC** [comment]
closing this for now because we can merge soon
