### ISSUE TITLE
prevent eslint false positives

### ISSUE THREAD

**Issue by MiniXC** [MEH-Design/frix#30]
We should [migrate to v2.0.0](http://eslint.org/docs/user-guide/migrating-to-2.0.0) in order to prevent false positives like the following:
<img src="http://i.imgur.com/Gz2ZuOT.png">

**Comment by MiniXC** [comment]
We are already running eslint, this has to be an issue with [CodeClimate](http://codeclimate.com).

**Comment by bminixhofer** [comment]
fixed in commit fc9f34c742629fa822fb887243bfa243f4f29680
