### ISSUE TITLE
hyphenated attributes cause crash

### ISSUE THREAD

**Issue by MiniXC** [MEH-Design/frix#80]
````html
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
````
The ``http-equiv`` tag is recognized as being specific to frix because of the hyphen it contains, which causes the core to stop.

**Comment by bminixhofer** [comment]
This was fixed in 7caeef7da5fc1400e9e417cf202ec450bc3b65de. Frix now checks if, in this case, the `http` prefix exists. If not the attribute is ignored.

The problem persists if there is a prefix called `http` so we have to add some check to prevent this.
